### ISSUE TITLE
Error message about `SyntaxError: Unexpected token`

### ISSUE THREAD

**Issue by houshengbo** [nibalizer/case-watch-bot#4]
I cloned this repo locally and run thru the steps as in quickstart.
I did not change anything in .env.
npm version: npm@6.14.2 /usr/local/lib/node_modules/npm

Here is the error message I got, after running `npm start`.
```
vincent@VincentMacBookPro case-watch-bot % npm start        

> case-watch-bot@1.0.0 start /Users/vincent/go/src/github.com/nibalizer/case-watch-bot
> node main.js

/Users/vincent/go/src/github.com/nibalizer/case-watch-bot/node_modules/discord.js/src/client/Client.js:40
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vincent/go/src/github.com/nibalizer/case-watch-bot/node_modules/discord.js/src/index.js:8:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! case-watch-bot@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the case-watch-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vincent/.npm/_logs/2020-03-10T14_40_10_783Z-debug.log
```

**Comment by nibalizer** [comment]
I suspect you need either a valid `DISCORD_TOKEN` or to set `DISCORD_POST` to `false`.  I am using npm 6.13.7 and node v13.9.0.

**Comment by houshengbo** [comment]
We need to install the newer version of node.js to go thru all the step:
Visit: https://nodejs.org/en/
Download the version, at least 12.16.1.
Run `npm install` then `npm start`.
The error would be gone.

**Comment by nibalizer** [comment]
Thanks!
